@echo off
echo Fixing .env file...
wsl sed -i "s/animalai.db/skinai.db/g" ~/hackaton/.env
echo Starting server...
wsl -d Ubuntu -e bash -c "cd ~/hackaton && source venv/bin/activate && uvicorn app.main:app --reload --host 0.0.0.0"
